### ISSUE TITLE
Save process is unclear

### ISSUE THREAD

**Issue by Dubzer** [darx/IndexedDBEdit#1]
Hi. 
Thanks for the extension. I just found it in the store, and it really helped me.
The first thing I encountered was finding the "Save" button. As I then read in the source code, it looks like the extension saves changes automatically when defocusing from the DevTools. But it wasn't clear for me at all.
I think, there's room for improvement

**Comment by darx** [comment]
Will publish an update in the coming days, thank you for your feedback.
