### ISSUE TITLE
Fails to parse info

### ISSUE THREAD

**Issue by SirAngle** [darx/IndexedDBEdit#10]
Greetings, I've used the app to extract large amounts of data, but some of it simply isn't saved. It appears it doesn't know how to deal with a date object.
Example

Position: 0
Key: 543123
Value: {createDate: Tue May 31 2022 08:18:00 GMT+0300 (שעון ישראל (קיץ))}

What your extension shows is
```
"key": 543123,
"value": {
            "createDate": {},
}
```

The error occurs either because it bugs out due to the date object, or due to the fact there is an ':' in it.
Thank you for the app!

**Comment by darx** [comment]
Hi @SirAngle,

Thank you for taking the time to raise this issue,

I'll make sure to notify you in the next couple of days when a patch is released.

**Comment by SirAngle** [comment]
Greetings, will the patch be released anytime soon?

**Comment by darx** [comment]
Hi @SirAngle,

Will be going out shortly.

Once this issue is closed the update will be live on the Chrome Web Store.
