### ISSUE TITLE
Records view does not work very well with large collections.

### ISSUE THREAD

**Issue by jcblw** [darx/IndexedDBEdit#5]
I have a few web extension I have been using this to debug the background process, and most of them have pretty large amount of records. I found this extension by searching on the CWS and thought it was great, but often can't use it because I am unable to find items in the records, and kinda wish there was a way to search by the indexes on the tables. I would love to help out if you have any ideas on how this can work, or what this would look like.

![Screen Shot 2022-07-09 at 1 42 09 PM](https://user-images.githubusercontent.com/578259/178121978-ea96c847-dcdf-45f9-88cf-65a7d22f3023.png)

**Comment by darx** [comment]
Hi @jcblw, 

Thank you for the feedback much appreciated, please feel free to suggest any other useful additions for the tool.

I will push an update in the next few days which will include search / replace functionality. You should get a notification when the update goes live.

(⬇️ Video Preview ⬇️ )

https://user-images.githubusercontent.com/3826878/179307541-0604e497-0e3e-4fbc-9653-9de328f92845.mp4

**Comment by jcblw** [comment]
Amazing looks great!
