### ISSUE TITLE
Error while saving Data!

### ISSUE THREAD

**Issue by afzali** [darx/IndexedDBEdit#7]
First, thank you for writing the only indexed dB editor extension available. But the main problem here is that it doesn't work!
VM145:12 Uncaught DOMException: Failed to execute 'put' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.
    at request.onsuccess (<anonymous>:12:19)

**Comment by darx** [comment]
Hi @afzali ,

Thank you for taking the time to raise this issue.

Can you please provide me with an example on how to reproduce this issue?

Is there a site I can visit or a GitHub repo which I clone which contains the IndexedDB table schema?

Any additional information which you could provide would be much appreciated.

**Comment by afzali** [comment]
I wrote an offline web site with svelte and dexie, but I can't use your extension.
[https://arzaaq.ir/](https://arzaaq.ir/)
Enter the website and write whatever you like in the form and then press the green button or better use Google translation to enter the site.
Then open your extension and go to user store  and you will see that you cannot edit anything in the site database.

**Comment by darx** [comment]
Hi @afzali ,

Thanks for getting back to me.

Leave it with me; I'll get back to you shortly with an update.

**Comment by darx** [comment]
Hi @afzali ,

New version has been publish (Version : 0.0.6), please visit [chrome://extensions/?id=npjecebdjnmlolggnoajngnlodhgpfac](chrome://extensions/?id=npjecebdjnmlolggnoajngnlodhgpfac)

Click "Update" button to get the newest version:
![Screenshot 2022-07-29 at 18 19 38](https://user-images.githubusercontent.com/3826878/181811412-7e5aa0bc-c255-4512-bb5d-6384ce667377.png)

Let me know if you have any further issues.

**Comment by afzali** [comment]
excellent.👌
Thank you for your quick and correct answer.
As a suggestion, it would be very good to design a proper user interface (gui) similar to the one in the Dev panel for more convenience, 
of course it is still good.

**Comment by darx** [comment]
Hi @afzali ,

Thank you for the feedback. UI improvements will be coming.
